### ISSUE TITLE
intu manager can't open on MacOS 10.12.1

### ISSUE THREAD

**Issue by swizardlv** [watson-intu/self-sdk#2]
the chinese words mean "application Intu manager can't be opened".

![image](https://cloud.githubusercontent.com/assets/10117682/20251020/6c4ba718-aa50-11e6-8fa5-262f7f7980fb.png)

**Comment by gitwouter** [comment]
It possible that you need to right-click and then select 'open'. This is typical on Mac when you try to start an application downloaded from the web. You only need to do that the first time.

**Comment by ereneld** [comment]
It is not a bug but known issue. As @gitwouter mentioned you can right-click and then select 'open' then on the dialog you can see 'Open' button next to cancel button. That works.

**Comment by swizardlv** [comment]
@ereneld still not work for me. not the security issue.

**Comment by swizardlv** [comment]
@ereneld any update for this issue?
i am evaluating whether to leverage Intu in new project. need your help asap. thanks.

**Comment by ereneld** [comment]
Sorry for not updating, i was sick and out of work.
Could you paste log file under app? 
Right click on .app and show content, there is log file there. It may give a clue but it looks like the app has not started at all, so log should be empty in that case
There are 2 possible issues as far as i can say;
1- somehow the .app file you have modified and mac can't open due to hash check. It behaves like a corrupt application. It may be due to unzipping process on your machine or on our end. Please re-download and unzip with different program. 
2 - the graphic card is not supported somehow or the drivers on your machine may not be suitable. I can send a test application to understand the issue.

**Comment by swizardlv** [comment]
@ereneld sorry to hear that you were sick. hope you are better now.
it's the issue 1. i extracted the zip using "unzip" in CLI. it didn't work. and also used "keka", didn't work either. when i switched to the mac build-in tool, it worked.
I think the intu manager should be zipped using CLI then all unarchive tools can work well.

Thanks.

**Comment by ereneld** [comment]
@swizardlv glad that it worked. We will check the build machine process. I guess it is using mac build-in zip. Thanks.
